export interface IChurchResponse {
    churchID?:number;
    name:string;
    address:string;
    longitude?:string;
    latitude?:string;
    churchLogo?:string;
    denominationId:number;
    denomination?:string;
    dioceseId?:number;
    deanaryId?:number;
    provinceId?:number;
    regionId?:number;
    stateName?:string;
    cityName?:string;
    countryID:number;
    stateID:number;
    cityID:number;
}